### PR TITLE
Add usage, default generated jigsaw

### PR DESCRIPTION
**Pull request by jonadem**

### CODE REVIEW

**Comment by Neon22** [comment]
Thanks....

**Comment by jonadem** [comment]
It's me would should thank you.

To improve things a little more, could you add an image on https://inkscape.org/~Neon22/%E2%98%85lasercut-jigsaw ?
I would be really nice ! :-)

**Comment by Neon22** [comment]
I did have a nice one but when I lost my machine I lost the image. I need to remake i guess :)

**Comment by Neon22** [comment]
done. thanks for your svg. used it.

**Comment by jonadem** [comment]
Thx !

**Pull request merged**
